#!/bin/bash

#### Regular Colors
RED="\033[1;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
CYAN="\033[1;36m"
GREY="\033[0;37m"
RESET="\033[m"
BOLDGREEN="\033[1;32m"
BOLDRED="\033[1;31m"
ENDCOLOR="\e[0m"

#### Variables
NATIVEFIER="nativefier"
DIVIDER="=================================================="
DV2="echo -e "${BOLDRED}$DIVIDER${ENDCOLOR}""
VERSION="ALTER_desktop-0.0.5-alpha for Linux-x64"

#### Commands
COMM1="sudo npm -g install nativefier"
COMM2="cp ALTER.desktop $HOME/.local/share/applications/"
COMM3="sudo cp alter.png /usr/share/icons/alter.png"
COMM4="nativefier --version"
COMM5="nativefier --name ALTER --platform linux --arch x64 --width 1634 --height 1355 --tray --disable-dev-tools --single-instance https://app.altermail.live/login"
COMM7="sudo cp -r ALTER-linux-x64 /usr/bin/ALTER_desktop"

#### Message Lines
MSG1="ALTER_desktop is an unofficial nativefier application and not affiliated with the ALTER team"
MSG2="Please feel free to leave any feedback to"
MSG3="You can also send me a message on ALTER"

#### Email
EMAIL1="james@scrtnetwork.co"
EMAIL2="kusanagi.2029@protonmail.com"
ALTER="az4jnb2ngz"

#### URLs
URLS="https://reversesigh.info - https://github.com/reversesigh"

#### Script Messages
SM1="Checking for 'nativefier' on system"
SM2="Copying ALTER.desktop to ~/.local/share/applications/"
SM3="Copying alter.png to /usr/share/icons/"
SM4="Creating ALTER_desktop"
SM5="Moving ALTER-linux-x64 to ALTER_desktop"
SM6="Copying ALTER to /usr/bin/ALTER_desktop"
SM7="Please check your settings and environment"
SM8="Find it in your applications list or /usr/bin/ALTER_desktop/ALTER"

#### cat
CT1="cat variables"

#### Text
TX1="Nativefier"
TX2="NOT FOUND..."
TX3="Installing Nativefier"
TX4="Ntivefier already installed. Skipped."
TX5="Checking Nanofier Version......"

#### Random
RD1="command -v ./usr/bin/ALTER_desktop/ALTER"
RD2="command -v"

#### if then
IT1="echo -e "${CYAN}$TX1${ENDCOLOR}" "${BOLDRED}$TX2${ENDCOLOR}""
IT2="echo -e "${BOLDGREEN}$TX3${ENDCOLOR}""
IT3="echo -e "${BOLDGREEN}$TX4${ENDCOLOR}""
IT4="echo -e "${BOLDRED}WARNING${ENDOCLOR}" "${CYAN}Could not find${ENDCOLOR}" "${RED}ALTER_desktop${ENDCOLOR}"."
IT6="echo -e "${CYAN}$SM7${ENDCOLOR}""
IT7="echo -e "${GREY}$SM8${ENDCOLOR}""
IT8="$RD2 ${NATIVEFIER}"
IT9="hash $RD1"

#### echo Posts
EP1="echo -e "${RED}$VERSION${ENDCOLOR}""
EP2="echo -e "${BOLDGREEN}$SM2${ENDCOLOR}""
EP3="echo -e "${BOLDGREEN}$SM3${ENDCOLOR}""
EP4="echo -e "${BOLDGREEN}$SM4${ENDCOLOR}""
EP5="echo -e "${BOLDGREEN}$SM5${ENDCOLOR}""
EP6="echo -e "${BOLDGREEN}$SM6${ENDCOLOR}""
EP7="echo -e "${BOLDGREEN}$SM1${ENDCOLOR}""
EP8="echo -e $TX5"

#### PM Codes
PM1="echo -e "${YELLOW}$MSG1${ENDCOLOR}""
PM2="echo -e "${YELLOW}$MSG2${ENDCOLOR}" "${GREY}$EMAIL1${ENDCOLOR}" or "${GREY}$EMAIL2${ENDCOLOR}""
PM3="echo -e "${YELLOW}$MSG3${ENDCOLOR}" "${GREY}$ALTER${ENDCOLOR}""
PM4="echo -e "${GREY}$URLS${ENDCOLOR}""
PM5="echo -e "${BOLDRED}$DIVIDER${ENDCOLOR}""

# ALTER_desktop-0.0.5-alpha - An Unofficial Desktop App for Linux-x64 wrapped with 'nativefier'

${CT1}

## Intro
     echo
     $EP1
     echo
     $DV2


## Checks for 'nativefier' via npm. If not found then uses npm to install nativefier.
     echo
     $EP7
     echo

if ! $IT8 >/dev/null; then

     $IT1
     echo
     $IT2
     $COMM1 "$@"
   else
     $IT3

fi

     echo
     $DV2
     echo


## Copies ALTER.desktop to local applications folder, allowing it to be discoverable in your applications list
     echo
     $EP2
     $COMM2
     echo


## Copies alter.png to your root icons folder to use the ALTER logo as the ALTER_dekstop icon
     $EP3
     $COMM3
     echo


## Creates wrapped web application using nativefier
     $EP4
     echo
     $DV2
     echo
     $EP8
     echo
     echo
     $COMM4
     $COMM5
     echo
     $DV2


## Move ALTER-linux-x64 to ALTER_desktop
     echo
     $EP5
     $COMM6
     echo


## Copying ALTER to /usr/bin/ALTER_desktop
     $EP6
     $COMM7
echo
     $DV2


## Checks to make sure installing ALTER_desktop was a success
if $IT9 2>/dev/null; then
     $IT4
     $IT6
     exit

   else
     echo
     echo
     $IT5
     echo
     echo
     $IT7
     echo
fi

     $DV2
     $PM1
     echo
     $PM2
     echo
     $PM3
     echo
     $PM4
     echo
     echo
     $PM5
