#!/bin/bash

#### Regular Colors
RED="\033[1;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
CYAN="\033[1;36m"
GREY="\033[0;37m"
RESET="\033[m"
BOLDGREEN="\033[1;32m"
BOLDRED="\033[1;31m"
ENDCOLOR="\e[0m"

#### Movement
RM="$(which rm)"
MV="$(which mv)"
CP="$(which cp)"

#### Variables
NATIVEFIER="nativefier"
DIVIDER="=================================================="
DV2="echo -e "${BOLDRED}$DIVIDER${ENDCOLOR}""
VERSION="ALTER_desktop-0.0.6-alpha for Linux-x64"

#### End Message
MSG1="ALTER_desktop is an unofficial nativefier application and not affiliated with the ALTER team"
MSG2="Please feel free to leave any feedback to"
MSG3="You can also send me a message on ALTER"

#### Email
EMAIL1="james@scrtnetwork.co"
EMAIL2="kusanagi.2029@protonmail.com"
ALTER="az4jnb2ngz"

#### URLs
URLS="https://reversesigh.info - https://github.com/reversesigh"

#### Check For
RD1="command -v $HOME/.local/share/ALTER_desktop/ALTER_desktop"

#### if then
IT0="find $HOME/.local/share/applications/ALTER.desktop"